return {
    'nvim-treesitter/nvim-treesitter',
    main = 'nvim-treesitter.configs',
    opts = {
        -- 'norg' and 'norg-meta' is handled by .build in ./neorg.lua
        ignore_install = {
            'norg',
            'norg-meta',
            'norg_old', -- Internal for Neorg?
        },
        ensure_installed = {
            'awk',
            'bash',
            'c',
            'cmake',
            'cpp',
            'css',
            'diff',
            'git_config',
            'git_rebase',
            'gitattributes',
            'gitcommit',
            'gitignore',
            'go',
            'gomod',
            'gosum',
            'gpg',
            'html',
            'ini',
            'javascript',
            'jq',
            'json',
            'lua',
            'make',
            'markdown',
            'markdown_inline',
            'ocaml',
            'perl',
            'python',
            'regex',
            'rust',
            'typescript',
            'vim',
            'vimdoc',
            'xml',
        },
        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = '<M-v>',
                node_incremental = '<M-v>',
                -- scope_incremental = 'grc',
                node_decremental = '<M-S-v>',
            },
        },
        additional_vim_regex_highlighting = false,
        highlight = { enable = true },
        indent = { enable = true },
        sync_install = false,
    },
}
